### ISSUE TITLE
Issue with UITableView as a Detail View in AppStore Transition

### ISSUE THREAD

**Issue by cyrilzakka** [marcosgriselli/EasyTransitions#15]
Hello!
First of all, great library! I'm experiencing a small issue when using a table view as the detail view in the AppStore transition. When dismissing it - but not completely - and releasing it before it actually dismisses so it returns back to the detail VC, the table view seems to distort. (width decreases it seems)

**Comment by marcosgriselli** [comment]
Hi @cyrilzakka thanks! I'll be changing the library a lot on the upcoming days so as soon as I finish that I'll add a few examples of different common scenarios so you can use them.
