### ISSUE TITLE
Add transition to present ViewController with gesture.

### ISSUE THREAD

**Issue by bfernandesbfs** [marcosgriselli/EasyTransitions#19]
Hi guys,

Simulate swipe of Notification center, when user swipe of any orientation for sample, started transition to present second viewcontroller. the effect opposite PresentationControllerAnimator

**Comment by marcosgriselli** [comment]
Added a quick example on the BasePresentationController class (uncomment `window?.rootViewController = BasePresentationViewController()` from the `AppDelegate` to see it) for presenting a view controller interactively. It's swipe from the bottom to present and then swipe on the presented view controller to dismiss. 

![screenflow](https://user-images.githubusercontent.com/14804033/42411980-8e4e8ccc-81db-11e8-9fd0-eff94aedb60f.gif)
