### ISSUE TITLE
which library this animation can for android ?

### ISSUE THREAD

**Issue by android-shiyan** [marcosgriselli/EasyTransitions#21]
I am a andorid developer from china,I think good for this library about EayTransitions.But I think do it on Android App. Can you give me a good idea? thanks!

**Comment by marcosgriselli** [comment]
Hey @android-shiyan I don’t know much about android development. I do know they have something called Motion Layout that can help you achieve transitions like this. That’s all I can help you with. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
