### ISSUE TITLE
Music player like apple music?

### ISSUE THREAD

**Issue by cemalsayin** [marcosgriselli/EasyTransitions#29]
Hi Mr. Griselli, 
I want to create podcast player like apple music. I use some pods and review example for this. However i can't find any reason for create mini player like apple music. If i use your pod can i create mini player?

![Screen Shot 2019-08-21 at 15 04 07](https://user-images.githubusercontent.com/35407261/63570340-72de3c00-c585-11e9-8437-1746d39ec4a0.png)

**Comment by marcosgriselli** [comment]
@cemalsayin I'm not sure how that transition from mini-player to full-screen is achieved. You could potentially do it with EasyTransitions but I recommend you take a look at https://github.com/HarshilShah/DeckTransition which implements that transition perfectly.
